name: action

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: 发送 Telegram 通知！
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          📢📢📢恭喜个人定制固件顺利编译完成啦!!!📢📢📢
          完成时间：${{ env.FILE_DATE }}          
              
          发布地址：
          https://github.com/Cccccircle/Lede-Circle/releases
          
          👇👇👇👇👇下载请!!!👇👇👇👇👇
    
          奶牛快传：
          🥇🥇🥇${{ env.COWTRANSFER_URL }}🥇🥇🥇
                 
          WeTransfer：
          🥈🥈🥈${{ env.WETRANSFER_URL }}🥈🥈🥈
              
          🎁🎁🎁🎁🎁网盘只有7天时效,请及时完成更新!!!🎁🎁🎁🎁
